name: CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy code
        run: |
          cd /root/laboratoire5

          git fetch origin
          git reset --hard origin/main

          cat > .env << 'EOF'
          ${{ secrets.ENV_FILE }}
          EOF
          chmod 600 .env

          docker network create labo05-network || true

          docker compose up -d --build

          docker ps
